export interface Course {
  id: string;
  title: string;
  provider: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  duration: string;
  rating: number;
  branch: string[];
  skills: string[];
  description: string;
  youtubeUrl: string;
  youtubeId: string;
  category: string;
  careerPaths: string[];
  semester_min: number;
  semester_max: number;
  prereq_cgpa: number;
}

export const ALL_COURSES: Course[] = [
  {
    id: 'CS101',
    title: 'Data Structures & Algorithms',
    provider: 'freeCodeCamp',
    difficulty: 'Intermediate',
    duration: '10 weeks',
    rating: 4.9,
    branch: ['Computer Science', 'Information Technology', 'Data Science'],
    skills: ['DSA', 'Python', 'Problem Solving'],
    description: 'Master data structures, algorithms, and time complexity. Essential for coding interviews and software engineering.',
    youtubeUrl: 'https://www.youtube.com/watch?v=pkYVOmU3MgA',
    youtubeId: 'pkYVOmU3MgA',
    category: 'Core CS',
    careerPaths: ['Software Engineer', 'Backend Developer', 'Competitive Programmer'],
    semester_min: 2,
    semester_max: 6,
    prereq_cgpa: 5.5,
  },
  {
    id: 'CS102',
    title: 'Machine Learning & AI',
    provider: 'Stanford Online',
    difficulty: 'Advanced',
    duration: '3 months',
    rating: 4.9,
    branch: ['Computer Science', 'Data Science', 'Information Technology', 'Electronics & Communication'],
    skills: ['ML', 'Python', 'Statistics', 'NumPy'],
    description: 'Supervised/unsupervised learning, neural networks, model evaluation, and real-world projects.',
    youtubeUrl: 'https://www.youtube.com/watch?v=jGwO_UgTS7I',
    youtubeId: 'jGwO_UgTS7I',
    category: 'AI/ML',
    careerPaths: ['ML Engineer', 'Data Scientist', 'AI Researcher'],
    semester_min: 5,
    semester_max: 8,
    prereq_cgpa: 6.5,
  },
  {
    id: 'CS103',
    title: 'Cloud Computing & DevOps',
    provider: 'TechWorld with Nana',
    difficulty: 'Intermediate',
    duration: '6 weeks',
    rating: 4.8,
    branch: ['Computer Science', 'Information Technology', 'Data Science'],
    skills: ['AWS', 'Docker', 'CI/CD', 'Kubernetes'],
    description: 'AWS/GCP/Azure, CI/CD pipelines, containerization with Docker & Kubernetes. Industry-standard DevOps.',
    youtubeUrl: 'https://www.youtube.com/watch?v=3c-iBn73dDE',
    youtubeId: '3c-iBn73dDE',
    category: 'Infrastructure',
    careerPaths: ['DevOps Engineer', 'Cloud Architect', 'SRE'],
    semester_min: 5,
    semester_max: 8,
    prereq_cgpa: 5.5,
  },
  {
    id: 'CS104',
    title: 'Python Full Course for Beginners',
    provider: 'Programming with Mosh',
    difficulty: 'Beginner',
    duration: '6 hours',
    rating: 4.9,
    branch: ['Computer Science', 'Data Science', 'Mechanical', 'Electronics & Communication', 'Information Technology'],
    skills: ['Python', 'OOP', 'Scripting'],
    description: 'Complete Python tutorial from beginner to advanced. Variables, loops, functions, OOP, and more.',
    youtubeUrl: 'https://www.youtube.com/watch?v=_uQrJ0TkZlc',
    youtubeId: '_uQrJ0TkZlc',
    category: 'Programming',
    careerPaths: ['Software Developer', 'Data Analyst', 'ML Engineer'],
    semester_min: 1,
    semester_max: 4,
    prereq_cgpa: 0,
  },
  {
    id: 'CS105',
    title: 'Deep Learning & Computer Vision',
    provider: 'Andrej Karpathy',
    difficulty: 'Advanced',
    duration: '4 months',
    rating: 4.9,
    branch: ['Computer Science', 'Data Science'],
    skills: ['PyTorch', 'CNNs', 'Transformers', 'Computer Vision'],
    description: 'Build neural networks from scratch. CNNs, RNNs, Transformers, attention mechanisms.',
    youtubeUrl: 'https://www.youtube.com/watch?v=VMj-3S1tku0',
    youtubeId: 'VMj-3S1tku0',
    category: 'AI/ML',
    careerPaths: ['Deep Learning Engineer', 'Computer Vision Engineer', 'AI Researcher'],
    semester_min: 6,
    semester_max: 8,
    prereq_cgpa: 7.0,
  },
  {
    id: 'CS106',
    title: 'Full Stack Web Development',
    provider: 'Traversy Media',
    difficulty: 'Intermediate',
    duration: '2 months',
    rating: 4.8,
    branch: ['Computer Science', 'Information Technology', 'Data Science'],
    skills: ['React', 'Node.js', 'MongoDB', 'HTML/CSS'],
    description: 'Build modern full-stack web apps with React, Node.js, Express, and MongoDB. Deploy to the cloud.',
    youtubeUrl: 'https://www.youtube.com/watch?v=1Rs2ND1ryYc',
    youtubeId: '1Rs2ND1ryYc',
    category: 'Web Development',
    careerPaths: ['Full Stack Developer', 'Frontend Developer', 'Backend Developer'],
    semester_min: 3,
    semester_max: 7,
    prereq_cgpa: 5.0,
  },
  {
    id: 'EC101',
    title: 'VLSI Design & Verilog HDL',
    provider: 'NPTEL',
    difficulty: 'Advanced',
    duration: '8 weeks',
    rating: 4.7,
    branch: ['Electronics & Communication'],
    skills: ['VLSI', 'Verilog', 'Digital Design', 'Cadence'],
    description: 'Digital circuit design, Verilog HDL, synthesis and simulation. ASIC design flow.',
    youtubeUrl: 'https://www.youtube.com/watch?v=IuyXDBjGDiA',
    youtubeId: 'IuyXDBjGDiA',
    category: 'Electronics',
    careerPaths: ['VLSI Engineer', 'Chip Designer', 'Embedded Systems Engineer'],
    semester_min: 4,
    semester_max: 8,
    prereq_cgpa: 6.0,
  },
  {
    id: 'EC102',
    title: 'Embedded Systems & IoT',
    provider: 'Dronebot Workshop',
    difficulty: 'Intermediate',
    duration: '10 weeks',
    rating: 4.6,
    branch: ['Electronics & Communication', 'Computer Science', 'Mechanical'],
    skills: ['Arduino', 'Raspberry Pi', 'C/C++', 'IoT Protocols'],
    description: 'Build real IoT projects with Arduino, Raspberry Pi, sensors, and cloud connectivity.',
    youtubeUrl: 'https://www.youtube.com/watch?v=ELYsyuhbQfY',
    youtubeId: 'ELYsyuhbQfY',
    category: 'Embedded Systems',
    careerPaths: ['Embedded Engineer', 'IoT Developer', 'Firmware Engineer'],
    semester_min: 3,
    semester_max: 7,
    prereq_cgpa: 5.5,
  },
  {
    id: 'ME101',
    title: 'SolidWorks CAD Design',
    provider: 'Udemy / MyCADsite',
    difficulty: 'Intermediate',
    duration: '8 weeks',
    rating: 4.7,
    branch: ['Mechanical'],
    skills: ['SolidWorks', 'CAD', '3D Modeling', 'Engineering Drawing'],
    description: 'Complete SolidWorks tutorial for mechanical engineers. 3D modeling, assembly, and drawings.',
    youtubeUrl: 'https://www.youtube.com/watch?v=6Rc5gp5bXqI',
    youtubeId: '6Rc5gp5bXqI',
    category: 'CAD/CAM',
    careerPaths: ['Mechanical Designer', 'Product Engineer', 'Manufacturing Engineer'],
    semester_min: 2,
    semester_max: 6,
    prereq_cgpa: 5.0,
  },
  {
    id: 'ME102',
    title: 'Finite Element Analysis (FEA)',
    provider: 'NPTEL',
    difficulty: 'Advanced',
    duration: '10 weeks',
    rating: 4.6,
    branch: ['Mechanical'],
    skills: ['ANSYS', 'FEA', 'Structural Analysis', 'MATLAB'],
    description: 'Structural, thermal, and fluid analysis using FEA. ANSYS Workbench tutorials.',
    youtubeUrl: 'https://www.youtube.com/watch?v=GJJGHJnx_TQ',
    youtubeId: 'GJJGHJnx_TQ',
    category: 'Simulation',
    careerPaths: ['Simulation Engineer', 'R&D Engineer', 'Aerospace Engineer'],
    semester_min: 5,
    semester_max: 8,
    prereq_cgpa: 6.5,
  },
  {
    id: 'DS101',
    title: 'Data Analysis with Python & Pandas',
    provider: 'Keith Galli',
    difficulty: 'Beginner',
    duration: '5 weeks',
    rating: 4.8,
    branch: ['Data Science', 'Computer Science', 'Information Technology'],
    skills: ['Pandas', 'NumPy', 'Matplotlib', 'Data Wrangling'],
    description: 'Learn data analysis, manipulation, and visualization using Python, Pandas, and Matplotlib.',
    youtubeUrl: 'https://www.youtube.com/watch?v=vmEHCJofslg',
    youtubeId: 'vmEHCJofslg',
    category: 'Data Science',
    careerPaths: ['Data Analyst', 'Business Analyst', 'Data Scientist'],
    semester_min: 2,
    semester_max: 6,
    prereq_cgpa: 5.0,
  },
  {
    id: 'DS102',
    title: 'SQL & Database Design',
    provider: 'Programming with Mosh',
    difficulty: 'Beginner',
    duration: '4 weeks',
    rating: 4.9,
    branch: ['Data Science', 'Computer Science', 'Information Technology', 'Mechanical', 'Electronics & Communication'],
    skills: ['SQL', 'MySQL', 'Database Design', 'Joins'],
    description: 'Master SQL from beginner to advanced. Queries, joins, stored procedures, and database design.',
    youtubeUrl: 'https://www.youtube.com/watch?v=7S_tz1z_5bA',
    youtubeId: '7S_tz1z_5bA',
    category: 'Database',
    careerPaths: ['Database Administrator', 'Data Analyst', 'Backend Developer'],
    semester_min: 1,
    semester_max: 5,
    prereq_cgpa: 0,
  },
  {
    id: 'GEN101',
    title: 'Git & GitHub for Beginners',
    provider: 'freeCodeCamp',
    difficulty: 'Beginner',
    duration: '1 week',
    rating: 4.8,
    branch: ['Computer Science', 'Data Science', 'Mechanical', 'Electronics & Communication', 'Information Technology'],
    skills: ['Git', 'GitHub', 'Version Control', 'Collaboration'],
    description: 'Learn version control with Git and collaborate on projects using GitHub. Essential for all engineers.',
    youtubeUrl: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
    youtubeId: 'RGOj5yH7evk',
    category: 'Tools',
    careerPaths: ['All Software Roles'],
    semester_min: 1,
    semester_max: 8,
    prereq_cgpa: 0,
  },
  {
    id: 'GEN102',
    title: 'Statistics for Data Science',
    provider: 'StatQuest',
    difficulty: 'Intermediate',
    duration: '6 weeks',
    rating: 4.9,
    branch: ['Data Science', 'Computer Science', 'Electronics & Communication'],
    skills: ['Statistics', 'Probability', 'Hypothesis Testing', 'Regression'],
    description: 'Probability, distributions, hypothesis testing, regression, and Bayesian reasoning explained clearly.',
    youtubeUrl: 'https://www.youtube.com/watch?v=qBigTkBLU6g',
    youtubeId: 'qBigTkBLU6g',
    category: 'Statistics',
    careerPaths: ['Data Scientist', 'ML Engineer', 'Research Analyst'],
    semester_min: 3,
    semester_max: 7,
    prereq_cgpa: 5.5,
  },
  {
    id: 'GEN103',
    title: 'System Design Interview Prep',
    provider: 'Gaurav Sen',
    difficulty: 'Advanced',
    duration: '4 weeks',
    rating: 4.8,
    branch: ['Computer Science', 'Information Technology'],
    skills: ['System Design', 'Scalability', 'Microservices', 'Architecture'],
    description: 'Design scalable systems like Netflix, WhatsApp, and Twitter. Learn microservices, caching, and load balancing.',
    youtubeUrl: 'https://www.youtube.com/watch?v=xpDnVSmNFX0',
    youtubeId: 'xpDnVSmNFX0',
    category: 'Core CS',
    careerPaths: ['Senior Software Engineer', 'System Architect', 'Staff Engineer'],
    semester_min: 6,
    semester_max: 8,
    prereq_cgpa: 7.0,
  },
  {
    id: 'GEN104',
    title: 'Cybersecurity & Ethical Hacking',
    provider: 'TCM Security',
    difficulty: 'Intermediate',
    duration: '8 weeks',
    rating: 4.7,
    branch: ['Computer Science', 'Information Technology', 'Electronics & Communication'],
    skills: ['Network Security', 'Penetration Testing', 'Cryptography', 'Linux'],
    description: 'Learn ethical hacking, penetration testing, and network security. Kali Linux, Metasploit, Wireshark.',
    youtubeUrl: 'https://www.youtube.com/watch?v=3Kq1MIfTWCE',
    youtubeId: '3Kq1MIfTWCE',
    category: 'Security',
    careerPaths: ['Security Engineer', 'Ethical Hacker', 'SOC Analyst'],
    semester_min: 4,
    semester_max: 8,
    prereq_cgpa: 6.0,
  },
];

export function recommendCourses(
  branch: string,
  semester: number,
  cgpa: number,
  count = 5
): Course[] {
  const scored = ALL_COURSES.map(c => {
    let score = 0;
    if (c.branch.includes(branch)) score += 40;
    if (semester >= c.semester_min && semester <= c.semester_max) score += 25;
    if (cgpa >= c.prereq_cgpa) score += 20;
    score += c.rating * 3;
    return { ...c, score };
  });
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, count);
}

export const DIFF_COLOR: Record<string, string> = {
  Beginner: '#10b981',
  Intermediate: '#fbbf24',
  Advanced: '#f43f5e',
};
